before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
    ldflags:
      - -s -w -extldflags=-static
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
    - "ghcr.io/buckaroobanzay/minetest-web:{{ .Version }}"
    - "ghcr.io/buckaroobanzay/minetest-web:latest"
  dockerfile: Dockerfile