version: "3.6"

services:
 web_ui:
  image: node:19.2.0-alpine3.15
  volumes:
   - "./:/app"
  working_dir: /app/public
  command: ["npm", "ci"]

 web:
  image: golang:1.21.6
  environment:
   WEBDEV: "true"
  ports:
    - 8080:8080
  volumes:
   - "./:/app"
   - "go_dir:/go"
   - "go_cache:/.cache"
  working_dir: /app
  command: ["go", "run", "."]

 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.7.0
  user: root

volumes:
  go_cache: {}
  go_dir: {}