name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      # step for tags (v*)
      - name: Build and push tag
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          docker build . -t ghcr.io/buckaroobanzay/minetest-web:${RELEASE_VERSION}
          docker push ghcr.io/buckaroobanzay/minetest-web:${RELEASE_VERSION}

      # step for main/latest (docker only)
      - name: Build and push latest docker image
        if: success() && github.ref == 'refs/heads/main'
        run: |
          CGO_ENABLED=0 go build -ldflags="-s -w -extldflags=-static"
          docker build . -t ghcr.io/buckaroobanzay/minetest-web:latest
          docker push ghcr.io/buckaroobanzay/minetest-web:latest
